CRITICAL - 2021-12-13 03:47:02 --> Call to a member function isValid() on array
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 03:47:48 --> Undefined array key 0
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 03:52:22 --> Undefined array key 0
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:00:42 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:03:44 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:04:48 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:05:23 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:06:20 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:08:02 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:09:30 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(168): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 168)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:11:06 --> Trying to access array offset on value of type null
#0 /app/app/Controllers/User.php(168): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to acces...', '/app/app/Contro...', 168)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:12:29 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 04:12:53 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 04:14:56 --> Array to string conversion
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:15:39 --> Array to string conversion
#0 /app/app/Controllers/User.php(167): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', '/app/app/Contro...', 167)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 04:20:19 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 04:26:25 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 04:27:37 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 04:38:46 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:40:10 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:42:31 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:43:44 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:44:41 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:45:28 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:46:57 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:47:25 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:49:36 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:50:38 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:50:43 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:55:41 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:57:06 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:58:03 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:58:43 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:59:18 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:59:44 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 04:59:59 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 05:01:29 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 05:02:12 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 05:02:55 --> Declaration of App\Filters\Options::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 05:04:58 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 05:05:45 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-12-13 06:04:28 --> Table 'glimradb.user_hashtag' doesn't exist
CRITICAL - 2021-12-13 06:04:28 --> Table 'glimradb.user_hashtag' doesn't exist
#0 /app/system/Database/MySQLi/Connection.php(292): mysqli->query('SELECT * FROM u...', 0)
#1 /app/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM u...')
#2 /app/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM u...')
#3 /app/app/Models/HashtagModel.php(112): CodeIgniter\Database\BaseConnection->query('SELECT * FROM u...')
#4 /app/app/Controllers/Hashtag.php(127): App\Models\HashtagModel->get_all_user_hashtags()
#5 /app/system/CodeIgniter.php(824): App\Controllers\Hashtag->get_all_user_hashtags()
#6 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Hashtag))
#7 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-13 06:15:04 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 06:17:09 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2021-12-13 06:17:40 --> Unknown column 'password' in 'field list'
CRITICAL - 2021-12-13 06:17:40 --> Unknown column 'password' in 'field list'
#0 /app/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO use...', 0)
#1 /app/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO use...')
#2 /app/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO use...')
#3 /app/app/Models/UserModel.php(87): CodeIgniter\Database\BaseConnection->query('INSERT INTO use...')
#4 /app/app/Controllers/User.php(230): App\Models\UserModel->create_user(Object(stdClass))
#5 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#6 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-13 06:19:57 --> Attempt to read property "name" on null
#0 /app/app/Controllers/User.php(204): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Contro...', 204)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 06:43:18 --> Attempt to read property "name" on null
#0 /app/app/Controllers/User.php(199): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Contro...', 199)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-12-13 06:44:47 --> Unknown column 'time' in 'field list'
CRITICAL - 2021-12-13 06:44:48 --> Unknown column 'time' in 'field list'
#0 /app/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO pos...', 0)
#1 /app/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO pos...')
#2 /app/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO pos...')
#3 /app/app/Models/PostModel.php(36): CodeIgniter\Database\BaseConnection->query('INSERT INTO pos...')
#4 /app/app/Controllers/Post.php(142): App\Models\PostModel->create_post(Object(stdClass))
#5 /app/system/CodeIgniter.php(824): App\Controllers\Post->create_post()
#6 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Post))
#7 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-13 06:57:39 --> Array to string conversion
#0 /app/app/Controllers/User.php(187): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', '/app/app/Contro...', 187)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:10:31 --> Attempt to read property "name" on null
#0 /app/app/Controllers/User.php(199): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Contro...', 199)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:11:31 --> Attempt to read property "name" on null
#0 /app/app/Controllers/User.php(201): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Contro...', 201)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:11:53 --> Attempt to read property "name" on null
#0 /app/app/Controllers/User.php(203): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Contro...', 203)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:14:17 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 07:19:04 --> Array to string conversion
#0 /app/app/Controllers/User.php(203): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', '/app/app/Contro...', 203)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:19:09 --> Array to string conversion
#0 /app/app/Controllers/User.php(203): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', '/app/app/Contro...', 203)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:32:53 --> syntax error, unexpected identifier "print_r"
#0 /app/system/Router/Router.php(176): CodeIgniter\Router\Router->autoRoute('user/create_use...')
#1 /app/system/CodeIgniter.php(718): CodeIgniter\Router\Router->handle('user/create_use...')
#2 /app/system/CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:33:07 --> syntax error, unexpected variable "$user_model", expecting "function" or "const"
#0 /app/system/Router/Router.php(176): CodeIgniter\Router\Router->autoRoute('user/create_use...')
#1 /app/system/CodeIgniter.php(718): CodeIgniter\Router\Router->handle('user/create_use...')
#2 /app/system/CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:33:40 --> Undefined variable $user_model
#0 /app/app/Controllers/User.php(210): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', '/app/app/Contro...', 210)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:36:49 --> Attempt to read property "name" on array
#0 /app/app/Models/UserModel.php(87): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', '/app/app/Models...', 87)
#1 /app/app/Controllers/User.php(238): App\Models\UserModel->create_user(Array)
#2 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#3 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 07:39:21 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:39:22 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:43:34 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:46:06 --> Undefined array key "data"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:46:08 --> Undefined array key "data"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:48:24 --> Undefined array key "data"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:49:23 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 07:51:42 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 08:00:49 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 08:04:45 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(206): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 206)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2021-12-13 08:14:04 --> Column count doesn't match value count at row 1
CRITICAL - 2021-12-13 08:14:05 --> Column count doesn't match value count at row 1
#0 /app/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO use...', 0)
#1 /app/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO use...')
#2 /app/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO use...')
#3 /app/app/Models/UserModel.php(87): CodeIgniter\Database\BaseConnection->query('INSERT INTO use...')
#4 /app/app/Controllers/User.php(238): App\Models\UserModel->create_user(Array)
#5 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#6 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-13 08:20:45 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:20:45 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:21:46 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 70)
#1 /app/app/Controllers/User.php(70): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:21:46 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:23:02 --> Undefined array key "data"
#0 /app/app/Controllers/User.php(179): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 179)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 08:26:01 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 70)
#1 /app/app/Controllers/User.php(70): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:26:01 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:27:35 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:27:35 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:29:30 --> Undefined array key "data"
#0 /app/app/Controllers/User.php(179): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 179)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 08:29:53 --> Undefined array key "body"
#0 /app/app/Controllers/User.php(179): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 179)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 08:30:23 --> Cannot use [] for reading
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:34:21 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:36:05 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:36:28 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:42:48 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:42:48 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:55:54 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:57:17 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:58:02 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:58:02 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:58:53 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:58:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:59:12 --> Cannot modify header information - headers already sent
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/app/Contro...', 52)
#1 /app/app/Controllers/User.php(52): header('Access-Control-...')
#2 /app/system/CodeIgniter.php(801): App\Controllers\User->__construct()
#3 /app/system/CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#4 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-13 08:59:12 --> Uncaught ErrorException: Cannot modify header information - headers already sent in /app/system/Debug/Exceptions.php:107
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', '/app/system/Deb...', 107)
#1 /app/system/Debug/Exceptions.php(107): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-12-13 08:59:34 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 08:59:43 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:00:01 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:00:41 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:01:01 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:01:18 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:01:31 --> Call to a member function isValid() on null
#0 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user_image()
#1 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-13 09:20:00 --> Undefined variable $request
#0 /app/app/Controllers/User.php(209): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', '/app/app/Contro...', 209)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 09:26:57 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(205): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 205)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-13 09:27:58 --> Undefined array key "name"
#0 /app/app/Controllers/User.php(205): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', '/app/app/Contro...', 205)
#1 /app/system/CodeIgniter.php(824): App\Controllers\User->create_user()
#2 /app/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#3 /app/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /app/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
